# Generated by Django 4.1.5 on 2023-01-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adhar_no',
            field=models.CharField(default=123, max_length=16),
            preserve_default=False,
        ),
    ]
