# Generated by Django 4.1.5 on 2023-01-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_adhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adhar_no',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
