from django.db import models
from django.core.exceptions import ValidationError


class User(models.Model):
    mail = models.EmailField(unique=True)
    name = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    phone = models.CharField(max_length=15,unique=True)
    adhar_no= models.CharField(max_length=16,unique=True)
    profilefill = models.CharField(max_length=3)

    def clean(self):
        if User.objects.filter(adhar_no=self.adhar_no).exclude(pk=self.pk).exists():
            raise ValidationError("Adhar Number already exists.")
        if User.objects.filter(phone=self.phone).exclude(pk=self.pk).exists():
            raise ValidationError("Phone Number already exists.")
        if User.objects.filter(mail=self.mail).exclude(pk=self.pk).exists():
            raise ValidationError("Email already exists.")

class AppliedUserScheme(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    applied_scheme = models.CharField(max_length=255)

class UserProfile(models.Model):
    phone_number = models.CharField(max_length=10,default=None)
    account_number = models.CharField(max_length=256,null=True,default=None)
    achievement = models.CharField(max_length=256, null=True,default=None)
    address = models.CharField(max_length=256, null=True,default=None)
    age = models.CharField(max_length=256,null=True,default=None)
    annual_income = models.CharField(max_length=256,null=True,default=None)
    bank_name = models.CharField(max_length=256, null=True,default=None)
    cast = models.CharField(max_length=256, null=True,default=None)
    collegeaddress = models.CharField(max_length=256, null=True,default=None)
    collegeheadname = models.CharField(max_length=256, null=True,default=None)
    collegename = models.CharField(max_length=256, null=True,default=None)
    course1board = models.CharField(max_length=256, null=True,default=None)
    course1marks = models.CharField(max_length=256,null=True,default=None)
    course1markstotal = models.CharField(max_length=256,null=True,default=None)
    course1medium = models.CharField(max_length=256, null=True,default=None)
    course1name = models.CharField(max_length=256, null=True,default=None)
    course1per = models.CharField(max_length=256,null=True,default=None)
    course1year = models.CharField(max_length=256, null=True,default=None)
    course2board = models.CharField(max_length=256, null=True,default=None)
    course2marks = models.CharField(max_length=256,null=True,default=None)
    course2markstotal = models.CharField(max_length=256,null=True,default=None)
    course2medium = models.CharField(max_length=256, null=True,default=None)
    course2name = models.CharField(max_length=256, null=True,default=None)
    course2per = models.CharField(max_length=256,null=True,default=None)
    course2year = models.CharField(max_length=256, null=True,default=None)
    course3board = models.CharField(max_length=256, null=True,default=None)
    course3name = models.CharField(max_length=256, null=True,default=None)
    course3per = models.CharField(max_length=256, null=True,default=None)
    course3year = models.CharField(max_length=256, null=True,default=None)
    courseacademicyear = models.CharField(max_length=256, null=True,default=None)
    courseduration = models.CharField(max_length=256, null=True,default=None)
    coursefees = models.CharField(max_length=256, null=True,default=None)
    coursefeespaid = models.CharField(max_length=256, null=True,default=None)
    coursefeesrequired = models.CharField(max_length=256, null=True,default=None)
    coursename = models.CharField(max_length=256, null=True,default=None)
    docaddressname = models.CharField(max_length=256, null=True,default=None)
    docaddressurl = models.CharField(max_length=256,null=True,default=None)
    docadmissionname = models.CharField(max_length=256, null=True,default=None)
    docadmissionurl = models.CharField(max_length=256,null=True,default=None)
    docageproofname = models.CharField(max_length=256, null=True,default=None)
    docageproofurl = models.CharField(max_length=256,null=True,default=None)
    doccourse1url = models.CharField(max_length=256,null=True,default=None)
    doccourse2url = models.CharField(max_length=256,null=True,default=None)
    doccourse3url = models.CharField(max_length=256,null=True,default=None)
    doccurrentfeename = models.CharField(max_length=256, null=True,default=None)
    doccurrentfeeurl = models.CharField(max_length=256,null=True,default=None)
    docincomename = models.CharField(max_length=256, null=True,default=None)
    docincomeurl = models.CharField(max_length=256,null=True,default=None)
    docpassbookurl = models.CharField(max_length=256,null=True,default=None)
    fname = models.CharField(max_length=255, null=True,default=None)
    sname = models.CharField(max_length=255, null=True,default=None)
    lname = models.CharField(max_length=255, null=True,default=None)
    email = models.CharField(max_length=256,null=True,default=None)
    phone = models.CharField(max_length=10, null=True,default=None)
    gender = models.CharField(max_length=10, null=True,default=None)
    dob = models.CharField(max_length=256,null=True,default=None)
    religious = models.CharField(max_length=255, null=True,default=None)
    parent_status = models.CharField(max_length=255, null=True,default=None)
    parent_phone = models.CharField(max_length=10, null=True,default=None)
    fathername = models.CharField(max_length=255, null=True,default=None)
    fatheroccupation = models.CharField(max_length=255, null=True,default=None)
    fatherincome = models.CharField(max_length=256,null=True,default=None)
    fatheralive = models.CharField(max_length=256,null=True,default=None)
    mothername = models.CharField(max_length=255, null=True,default=None)
    motheroccupation = models.CharField(max_length=255, null=True,default=None)
    motherincome = models.CharField(max_length=256,null=True,default=None)
    motheralive = models.CharField(max_length=256,null=True,default=None)
    totalearningmember = models.CharField(max_length=256,null=True,default=None)
    totalfamilymember = models.CharField(max_length=256,null=True,default=None)
    family_income = models.CharField(max_length=256,null=True,default=None)
    lastcoursename = models.CharField(max_length=255, null=True,default=None)
    lastcourseacademicyear = models.CharField(max_length=255, null=True,default=None)
    nameinpassbook = models.CharField(max_length=255, null=True,default=None)
    ifsc_code = models.CharField(max_length=255, null=True,default=None)
    pincode = models.CharField(max_length=6, null=True,default=None)
    docphotoidname = models.CharField(max_length=255, null=True,default=None)
    docphotoidurl = models.CharField(max_length=255, null=True,default=None)